spring.application.name=finwise

spring.datasource.url=jdbc:mysql://localhost:3307/finwise
spring.datasource.username=${DB_USER:finwise}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.locations=classpath:db/migration

finwise.jwt.secret=${JWT_SECRET}
finwise.jwt.expiration=${JWT_EXPIRATION:3600000}
finwise.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

app.cors.allowed-origins=http://localhost:5173